<?php

namespace Database\Seeders;

use App\Models\AuditLog;
use App\Models\User;
use Illuminate\Database\Seeder;

class AuditLogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Audit logs are automatically generated by the system
        // This creates initial seeding entry to demonstrate audit logging

        $admin = User::where('role', 'admin')->first();

        if ($admin) {
            AuditLog::firstOrCreate(
                [
                    'user_id' => $admin->id,
                    'action' => 'Database Seeding',
                    'model_type' => 'System',
                    'model_id' => 0,
                ],
                [
                    'user_id' => $admin->id,
                    'action' => 'Database Seeding',
                    'model_type' => 'System',
                    'model_id' => 0,
                    'old_values' => null,
                    'new_values' => ['status' => 'Database initialization completed'],
                    'ip_address' => '127.0.0.1',
                    'user_agent' => 'Laravel CLI',
                ]
            );
        }
    }
}
