<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subject List - Print</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }

        .print-header {
            text-align: center;
            padding: 20px;
            border-bottom: 2px solid #1e3a8a;
            margin-bottom: 20px;
        }

        .print-header h1 {
            font-size: 20px;
            font-weight: bold;
            color: #1e3a8a;
            margin-bottom: 5px;
        }

        .print-header p {
            font-size: 11px;
            color: #666;
            margin: 2px 0;
        }

        .print-info {
            display: flex;
            justify-content: space-between;
            gap: 20px;
            flex-wrap: wrap;
            font-size: 10px;
            color: #666;
            margin-bottom: 15px;
            padding: 0 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 0 10px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 11px;
        }

        th {
            background-color: #1e3a8a;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .print-footer {
            text-align: center;
            margin-top: 20px;
            padding: 15px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
        }

        .no-data {
            text-align: center;
            padding: 40px;
            color: #666;
        }

        @media print {
            body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }

            th {
                background-color: #1e3a8a !important;
                color: white !important;
            }
        }
    </style>
</head>
<body>
    <div class="print-header">
        <h1>{{ $college?->name ?? 'Manmohan Memorial Polytechnic' }}</h1>
        <p>{{ $college?->address ?? 'Department of Computer Science' }}</p>
        <p>Assigned Subject List</p>
    </div>

    <div class="print-info">
        <div>
            <p>Date: {{ now()->format('d-m-Y H:i') }}</p>
            <p>Total Subjects: {{ $subjectAssignments->count() }}</p>
        </div>
        <div>
            @if(!empty($filters['semester']))
                <p>Semester: {{ $filters['semester'] }}</p>
            @endif
            @if(!empty($filters['search']))
                <p>Search: {{ $filters['search'] }}</p>
            @endif
        </div>
    </div>

    @if($subjectAssignments->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 5%">S.N.</th>
                    <th style="width: 24%">Subject</th>
                    <th style="width: 12%">Code</th>
                    <th style="width: 20%">Course</th>
                    <th style="width: 8%">Semester</th>
                    <th style="width: 10%">Students</th>
                    <th style="width: 11%">Attendance</th>
                    <th style="width: 10%">Role</th>
                </tr>
            </thead>
            <tbody>
                @foreach($subjectAssignments->values() as $index => $assignment)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $assignment['subject_name'] ?? 'N/A' }}</td>
                        <td>{{ $assignment['subject_code'] ?? 'N/A' }}</td>
                        <td>{{ $assignment['course_name'] ?? 'N/A' }}</td>
                        <td>{{ $assignment['semester'] ?? 'N/A' }}</td>
                        <td>{{ $assignment['student_count'] ?? 0 }}</td>
                        <td>{{ number_format((float) ($assignment['attendance_rate'] ?? 0), 1) }}%</td>
                        <td>{{ ucfirst($assignment['role'] ?? 'teacher') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No subjects found.</p>
        </div>
    @endif

    <div class="print-footer">
        <p>Generated by Manmohan Memorial Polytechnic | {{ now()->format('d-m-Y H:i:s') }}</p>
    </div>
</body>
</html>

